name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Install dependencies
        run: dotnet restore GeoCop.sln

      - name: Build dotnet
        run: dotnet build GeoCop.sln -c Release --no-restore /warnaserror

      - name: Test
        run: dotnet test GeoCop.sln -c Release --no-build --verbosity normal

      - name: Run frontend ci
        working-directory: ./src/GeoCop.Frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./src/GeoCop.Frontend
        run: npm run build --if-present

      - name: Lint frontend
        working-directory: ./src/GeoCop.Frontend
        run: npm run lint
