name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      # Run the npm ci command before building
      # the dotnet project, because the project
      # itself calls npm install if the node_modules
      # folder does not exist.
      - name: Run frontend ci
        working-directory: ./src/GeoCop.Frontend
        run: npm ci

      - name: Install dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Build frontend
        working-directory: ./src/GeoCop.Frontend
        run: npm run build --if-present

      - name: Lint frontend
        working-directory: ./src/GeoCop.Frontend
        run: npm run lint
